version = 1

[[annotations]]
path = [
    "*.md",
    ".gitignore",
    "Makefile",
    "bin/**/*",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "**/*.go",
]
SPDX-FileCopyrightText = "Â© 2020 Vlad-Stefan Harbuz"
SPDX-License-Identifier = "Apache-2.0"
